
[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.normal]
family = "MonaspiceXe Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 0

[window]
dynamic_padding = false
dynamic_title = true

[window.padding]
x = 6
y = 6

[general]
live_config_reload = true
import = ["/home/lgs/.config/alacritty/themes/dracula.toml"]
